### PR TITLE
zephyr: Move glue code to zephyr

### PR DESCRIPTION
**Pull request by galak**
Move the glue code from living in the lvgl module to living
in the zephyr tree itself.

Signed-off-by: Kumar Gala <galak@kernel.org>

### Description of the feature or fix

A clear and concise description of what the bug or new feature is.

### Checkpoints
- [ ] Follow the [styling guide](https://github.com/lvgl/lvgl/blob/master/docs/CODING_STYLE.md)
- [ ] Run `code-format.py` from the `scripts` folder. [astyle](http://astyle.sourceforge.net/install.html) needs to be installed.
- [ ] Update the documentation

### CODE REVIEW

**Comment by brgl** [comment]
Any reason for doing this? We agreed two months ago to move the glue code into lvgl and that zephyr tree is not the right place for it.

**Comment by brgl** [comment]
I propose to close this as we've just recently moved this code out of the zephyr tree. @galak

**Comment by galak** [comment]
> I propose to close this as we've just recently moved this code out of the zephyr tree. @galak

Why was it moved out of the Zephyr tree?

**Comment by brgl** [comment]
> > I propose to close this as we've just recently moved this code out of the zephyr tree. @galak
> 
> Why was it moved out of the Zephyr tree?

[This](https://github.com/zephyrproject-rtos/zephyr/pull/41336) PR and associated issues have part of the story but most of it has been discussed during calls. In short: it should have never lived in the zephyr tree in the first place - just like all other third-party modules forks keep their zephyr-specific code locally under `zephyr/`. There's no advantage to keeping the glue code in the zephyr tree other than the Kconfig rigmarole we need to figure out. Having this code in the zephyr tree requires much more unnecessary effort when introducing support for new major releases as was the case with  LVGL 8.

**Comment by fabiobaltieri** [comment]
Hi, we ended up moving it in the end, didn't even realize that this has been filed at the time and not too happy that we keep kicking this code back and forth, clearly we are struggling to find a good compromise between "hard to keep up with LVGL api changes" and "hard to keep up with Zephyr changes" but that's where we are now.

Anyway, no point keeping this open anymore.

**Pull request closed without merging**
