### PR TITLE
Update to v7.6.1

### PR DESCRIPTION
**Pull request by vanwinkeljan**
Merged tag v7.6.1 in to zephyr branch

### CODE REVIEW

**Comment by vanwinkeljan** [comment]
This PR can not be merged as it contains a merge commit, I will push directly to the repo once I have approval

**Review by gmarull — CHANGES_REQUESTED** [review]
Missing files to CMakeLists.txt:

`lv_font_loader.c`

I wonder how they added 8px/10px Montserrat fonts, they don't seem to be listed together with other fonts.

**Comment by vanwinkeljan** [comment]
Added `lv_font_loader.c`

**Review by gmarull — APPROVED** [review]

**Review by carlescufi — APPROVED** [review]

**Comment by carlescufi** [comment]
@vanwinkeljan I assume you should push now, although you need to move to the model where PRs can be merged directly from the GitHub UI.

**Comment by tknapstad** [comment]
> Missing files to CMakeLists.txt:
> 
> `lv_font_loader.c`
> 
> I wonder how they added 8px/10px Montserrat fonts, they don't seem to be listed together with other fonts.

Source files for 8px and 10px Montserrat was added to 7.7.0 (which was tagged yesterday). It's not mentioned in the release notes.

**Comment by vanwinkeljan** [comment]
@tknapstad  thxs for the heads up

**Comment by vanwinkeljan** [comment]
Looks like after lvgl 7.7.0 is not yet officially released; github mentions 7.6.1 as latest release so let stick to 7.6.1

**Comment by gmarull** [comment]
@vanwinkeljan It is released:

https://github.com/lvgl/lvgl/releases/tag/v7.7.0
https://blog.lvgl.io/2020-10-20/release_v7.7.0

**Comment by vanwinkeljan** [comment]
@gmarull lvgl states on it is github page that 7.6.1 is the latest release (https://github.com/lvgl/lvgl/releases) and for some reason the release taged 7.7.0 is missing any form of release notes and is not marked as latest release.
Not sure if they just forget to update all this info or there is a known issue with this release.

**Comment by embeddedt** [comment]
I noticed this as well. Our release script might be having issues. I mentioned it to @kisvegabor [here](https://github.com/lvgl/lvgl/issues/1585#issuecomment-719999106).

**Comment by kisvegabor** [comment]
Ups, I forgot to make the release on GitHub. I set up an action to do this automatically on new tags.

**Pull request merged**
