### PR TITLE
Merge upstream LVGL 'v8.3.3' and resolve conflicts

### PR DESCRIPTION
**Pull request by diegoherranz**
Merge upstream LVGL 'v8.3.3' into Zephyr's fork and resolve conflicts

Update zephyr/CMakeLists.txt too.

Tested on a custom board with LCD display and Zephyr's samples/subsys/display/lvgl works OK.

Please note that the build process now emits a few notes like the following due to https://github.com/lvgl/lvgl/commit/c6b34bc85bb6f5e57e1c87857e03d1a0bd225e4c, which in turn refers to this GCC bug https://gcc.gnu.org/bugzilla/show_bug.cgi?id=80753.

`note: #pragma message: Possible failure to include lv_conf.h, please read the comment in this file if you get errors`

Should we define `LV_CONF_SUPPRESS_DEFINE_CHECK` to suppress that warning or leave it to the final user?

Thanks!

### CODE REVIEW

**Comment by diegoherranz** [comment]
Gentle ping. Thanks.

**Review by pdgendt — APPROVED** [review]
LGTM

@diegoherranz can you create a PR in the zephyr project to [update the module](https://docs.zephyrproject.org/3.2.0/develop/modules.html#process-for-submitting-changes-to-existing-modules)?

**Comment by diegoherranz** [comment]
> @diegoherranz can you create a PR in the zephyr project to [update the module](https://docs.zephyrproject.org/3.2.0/develop/modules.html#process-for-submitting-changes-to-existing-modules)?

Sure, I'll do.

What do you think we should do about these new warnings (from my first comment)?

> Please note that the build process now emits a few notes like the following due to https://github.com/lvgl/lvgl/commit/c6b34bc85bb6f5e57e1c87857e03d1a0bd225e4c, which in turn refers to this GCC bug https://gcc.gnu.org/bugzilla/show_bug.cgi?id=80753.

> note: #pragma message: Possible failure to include lv_conf.h, please read the comment in this file if you get errors

> Should we define LV_CONF_SUPPRESS_DEFINE_CHECK to suppress that warning or leave it to the final user?

Thanks!

**Comment by pdgendt** [comment]
> What do you think we should do about these new warnings (from my first comment)?

I think we could define the check to suppress the warning.

For example:
```c
// zephyr/lv_conf.h

#define LV_CONF_SUPPRESS_DEFINE_CHECK 1
```

**Comment by diegoherranz** [comment]
> I think we could define the check to suppress the warning.

Done: https://github.com/zephyrproject-rtos/lvgl/pull/33/commits/a283b66a87adae7172786dd8aa4ff2ce1c2bdb1e

> can you create a PR in the zephyr project to [update the module](https://docs.zephyrproject.org/3.2.0/develop/modules.html#process-for-submitting-changes-to-existing-modules)?

Done: https://github.com/zephyrproject-rtos/zephyr/pull/53974

Thanks!

**Review by denny61302 — APPROVED** [review]

**Comment by denny61302** [comment]
Not sure this is the right place to put my question.

I tried to speed up the performance of my GUI program and found this post on LVGL forum.

https://forum.lvgl.io/t/how-to-speed-up-the-v8-version/9091/21

Then I found this merge request so I downloaded and tested this v8.3.3 version.

Right now, I have the following that I haven't seen before. 

<err> lvgl: (385.993, +101)   _lv_inv_area: detected modifying dirty areas in render         (in lv_refr.c line #212)

**Pull request closed without merging**
