### PR TITLE
LVGL 9.2.0

### PR DESCRIPTION
**Pull request by faxe1008**
### Description of the feature or fix

A clear and concise description of what the bug or new feature is.

### Checkpoints
- [ ] Follow the [styling guide](https://github.com/lvgl/lvgl/blob/master/docs/CODING_STYLE.md)
- [ ] Run `code-format.py` from the `scripts` folder. [astyle](http://astyle.sourceforge.net/install.html) needs to be installed.
- [ ] Update the documentation

### CODE REVIEW

**Comment by faxe1008** [comment]
@pdgendt This was intentional, from now on I want to track the upstream repositories master (similar to how its done for nanopb). All parts needed for it to work as a Zephyr module have been upstreamed. In the past we had to make downstream modifications and ended up with a zephyr branch. Merging the new release into the zephyr one and continuing is not feasable as this causes a ton of merge conflicts due to our changes. 

There was this discussion about the modules tracking their parents: https://github.com/zephyrproject-rtos/zephyr/pull/75330
For the future I intend to follow the idea outlined by @aescolar, tracking master directly and if need be create a branch with prefix `zephyr_` with the fix that we can point to temporarily and upstream our changes eventually.

**Review by pdgendt — APPROVED** [review]

**Comment by pdgendt** [comment]
@faxe1008 is this ready to be merged? Kind of pointless to review, but it is needed for https://github.com/zephyrproject-rtos/zephyr/pull/68168

**Comment by faxe1008** [comment]
@pdgendt Yeah I mean if a forward does not hurt anything it can be merged, sure. If the requirement for the module PR is the mainrepo CI succeeding I still need https://github.com/zephyrproject-rtos/zephyr/pull/81263 to fix the tests.

**Comment by pdgendt** [comment]
Ok to merge now that the upstream is ready too?

**Comment by faxe1008** [comment]
Yes this one is mergable (but as fast forward without a merge commit)

**Comment by fabiobaltieri** [comment]
> Yes this one is mergable (but as fast forward without a merge commit)

GitHub says no, merge with merge is green, rebase merge says there's a conflict, and I think it would not fast forward anyway, wonder if one of us can push to master manually.

**Comment by fabiobaltieri** [comment]
```
$ git push git@github.com:zephyrproject-rtos/lvgl.git FETCH_HEAD:master
...
To github.com:zephyrproject-rtos/lvgl.git
   5d91c2472..6decbb7f7  FETCH_HEAD -> master
```

happy enough... ok so now you are going to switch the manifest to point at a commit in the master branch and the zephyr one is just going to stay there for saving the objects right?

**Comment by faxe1008** [comment]
> ok so now you are going to switch the manifest to point at a commit in the master branch and the zephyr one is just going to stay there for saving the objects right?

Yup exactly that is the plan. Thank you 👍

**Comment by fabiobaltieri** [comment]
ok cool, I pushed the current "zephyr" branch to a "v4.0-branch" branch as well so there's no ambiguity on what's that used to be used on, seen other modules doing it so it should be alright

**Comment by Tooniis** [comment]
Any way to use this before it lands in the zephyr branch?

**Pull request merged**
